
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor Production --target lib/main_production.dart --no-tree-shake-icons"
      firebase_app_distribution(
            app: "1:575687439560:android:1e710834e8f31a6ade61fd",
            firebase_cli_token: "1//03CUPkeyWBvM-CgYIARAAGAMSNwF-L9IrARPwuxb1dPR_-Ichga8p_JnvAxCvkBbX6D83QVqqLpAzkSNcpLIDdir1jHqkm4p43Sg",
            android_artifact_type:"APK",
            android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
            testers: "ahmedtramadan4@gmail.com",
            release_notes: "Release notes: for the Fastlane Distribution Doc App"
      )
  end
end
